### ISSUE TITLE
Clean shitcode.

### ISSUE THREAD

**Issue by itsVale** [itsVale/Vale.py#3]
Simple thing: Clean the shitcode in `/cogs/discordpy.py`.

**Comment by jagmoreira** [comment]
I can help with this.
PEP 8 compliance, remove unused variables, add more functions, that sort of thing?

**Comment by itsVale** [comment]
Yes, that's what I'm looking for. If you want to do this, feel free. :)

**Comment by jagmoreira** [comment]
Can you give me some possible examples of the `search` parameter in this function:
https://github.com/itsVale/Vale.py/blob/171e60fb6094fc20c2624127b0a977f906df7a31/cogs/discordpy.py#L68

**Comment by itsVale** [comment]
The parameter is the user's input in a Discord text channel. For example: `sudo rtfd bot` -> `"bot"` would be the `search` parameter. `sudo rtfd get member` -> `"get member"` would be the `search` parameter.
