### ISSUE TITLE
Improve logging.

### ISSUE THREAD

**Issue by itsVale** [itsVale/Vale.py#4]
So this might be a bit more difficult one. The goal is to extend the logger configuration that can be found in `bot.py` so the bot stores logs in a folder `/logs/`.  
Refer to the official Python docs for the [logging](https://docs.python.org/3/library/logging.html) as they explain everything necessary and feature lots of examples. How you do that is all yours, but it should save logs to the directory, log bot events, log everything from the cogs in the appropriate logging level (`info`, `debug`, ...) and also log warnings and errors.

**Comment by artslob** [comment]
Hi. It should be one file log for all cogs or separate file for each cog?

**Comment by itsVale** [comment]
Hi there! First of all, thanks for your interest!  
  
If you make one log file for everything or separate files for each cog, that's all up to you.  
What I personally would care about is:  

 - Single logger configuration and initialization in `bot.py`
 - Store log files in a folder `/logs/` whose contents are not tracked by Git.
 - If the directory does not exist, the bot should automatically create it.
 - Log bot events as well as events in cogs and utility files at the appropriate level (`info`, `debug`, etc.)
 - Log warnings and errors
 - The logger should have one FileHandler and one StreamHandler so it will log to the terminal and the log file(s)

Appreciated but **not** necessary:

 - Extended customizability of the logger configuration, e.g. through a JSON file or a database table.
